---
hide_body: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: description
  label: Description
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: text
  hidden: false
  default: ''
- name: categories
  label: Categories
  type: tag_list
  hidden: false
  default: []
- name: tags
  label: Tags
  type: tag_list
  hidden: false
  default: []
- name: thumbnail
  label: Thumbnail
  type: text
  hidden: false
  default: ''
